version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: molino
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
      - "3000:3000"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./wordpress-theme:/var/www/html/wp-content/themes/theme
volumes:
  db_data: